@startuml Process View - Level 1

autonumber
skinparam packageStyle rect

title Create Resource

participant "DataAdministrationModule" as DAM <<component>>

-> DAM: POST resources/{...}

activate DAM

alt resource Created

  <-- DAM: Response status code - 201

else invalid input

  <-- DAM: Response status code - 400

else unauthorized

  <-- DAM: Response status code - 401

else resource already exists

  <-- DAM: Response status code - 409

else database unavailable

  <-- DAM: Response status code - 503

end

@enduml