@startuml Process View - Level 3

autonumber
skinparam packageStyle rect
skinparam defaultFontName JetBrains Mono

title GET Buildings with min and max floors

participant "Node Backend" as BE <<component>>
database "Mongo DataBase" as DB <<component>>

-> BE: GET buildings/filter?minFloors=1&maxFloors=5

'Find All'

activate BE

BE -> DB: find with min\n and max floors

activate DB

DB --> BE:

deactivate DB

  <-- BE: Response status code - 200

alt database unavailable

  <-- BE: Response status code - 503

end

@enduml