@startuml Process View - Level 3

autonumber
skinparam packageStyle rect
skinparam defaultFontName JetBrains Mono

title Find Optimized Path

participant "Prolog Backend" as BE <<component>>

-> BE: GET paths?originFloor={...}\n&destinationFloor={...}&originCel={...}\n&destinationCel={...}

activate BE

BE -> : GET /prolog/campus

BE <--: response

note over BE
    Campus data is processed and asserted
    to knowledge base
end note

loop for each floor
    BE -> : GET prolog/floorPlans/{floorId}

    BE <--: response

    note over BE
        Floor data is processed and asserted
        to knowledge base
    end note
end loop

<-- BE: response

@enduml