@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Create Elevator

participant "Back-End" as BE <<component>>
database "DataBase" as DB <<component>>

-> BE: POST elevators/{\n domainId?: domainId,\n brand?: brand, \n model?: model,\n serialNumber?: serialNumber,\n description?: description,\n elevatorPosition: {xposition: xposition, yposition: yposition},\n floors: [floorIds],\n building: buildingId\n}

alt user autothorized

'Find by Domain ID'

activate BE

BE -> DB: find elevator by domain id

activate DB

DB --> BE:

deactivate DB

alt domain Id already exists

  <-- BE: Response status code - 409

else database unavailable

  <-- BE: Response status code - 503

end

'Find by Building ID'

activate BE

BE -> DB: find building by building id

activate DB

DB --> BE:

deactivate DB

alt building not found

  <-- BE: Response status code - 404

else database unavailable

  <-- BE: Response status code - 503

end

'Find by Building ID'

activate BE

BE -> DB: find elevators by building id

activate DB

DB --> BE:

deactivate DB

alt database unavailable

  <-- BE: Response status code - 503

end


'Find by Floor ID'

activate BE

BE -> DB: find floor by floor id

activate DB

DB --> BE:

deactivate DB

alt floor not found

  <-- BE: Response status code - 404

else database unavailable

  <-- BE: Response status code - 503

end




activate BE

BE -> DB: save

activate DB

DB --> BE:

deactivate DB

alt elevator persisted

  <-- BE: Response status code - 201

else database unaveilable

  <-- BE: Response status code - 503

end

else user unauthorized

  <-- BE: Response status code - 401

end

@enduml